language: objective-c
osx_image: xcode8
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - swift test
after_success:
  - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/feature/swift/package_detection/codecov)
